services:
  app:
    container_name: 'java-spring-crm-uralintern'
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db-postgres
    environment:
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-postgres:5432/internships
      - SPRING_DATASOURCE_USERNAME=crm_admin
      - SPRING_DATASOURCE_PASSWORD=bitrix24
      - SECURITY_JWT_SECRET=kkpCT7HHsKjkXCfVKzz7JA9Dgwhkg0xXqequdWhH60onkqPnU83hZ831b3eOYvyQdMytDFNfjMwZUBC3DHYaRg==
      - SECURITY_JWT_EXPIRATION=86400000
      - SECURITY_JWT_REFRESH_EXPIRATION=604800000
      - SPRINGDOC_SWAGGER_UI_URL=/swagger.json
      - SERVER_SERVLET_CONTEXT_PATH=/api
    command: ["sh", "-c", "while ! nc -z db-postgres 5432; do sleep 1; done; java -jar build/libs/CRM-Module-1.0-SNAPSHOT.jar"]
    restart: always
    networks:
      - main-network

  db-postgres:
    image: postgres:latest
    container_name: "database_postgres"
    environment:
      POSTGRES_DB: internships
      POSTGRES_USER: crm_admin
      POSTGRES_PASSWORD: bitrix24
    volumes:
      - ./backend/postgres-data:/var/lib/postgresql/data
      - ./backend/data/init-script.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    networks:
      - main-network
  
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-app
    restart: always
    networks:
      - main-network

  nginx:
    image: nginx:latest
    container_name: 'nginx-reverse-proxy'
    depends_on:
      - app
      - frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certificates:/etc/nginx/certificates:ro
    restart: always
    networks:
      - main-network
  
  telegram-bot:
    container_name: 'telegram-bot-crm'
    build:
      context: ./backend/telegram-service
      dockerfile: Dockerfile
    depends_on:
      - db-postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-postgres:5432/internships
      - SPRING_DATASOURCE_USERNAME=crm_admin
      - SPRING_DATASOURCE_PASSWORD=bitrix24
      - TELEGRAM_BOT_USERNAME=${TELEGRAM_BOT_USERNAME}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    restart: always
    networks:
      - main-network


networks:
  main-network:
    driver: bridge